[package]
name = "beeno"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
boa_engine = "0.20"
clap = { version = "4.5", features = ["derive"] }
